before_script:
  - chmod +x gradlew
stages:
  - build
build:
  stage: build
  tags:
    - build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/*.apk
